name: Data sharing between multi-jobs
on: workflow_dispatch

jobs:
  job_1:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ steps.step_1.outputs.my-value }}
      output_2: ${{ steps.step_2.outputs.my-value }}
    steps:
    - id: step_1
      run: echo "::set-output name=my-value::apple"
    - id: step_2
      run: echo "::set-output name=my-value::banana"
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
    - run: echo ${{needs.job_1.outputs.output_1}} ${{needs.job_1.outputs.output_2}}

