name: Job Pattern - Serial
on: push

jobs:
  job_a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A step in job A"
  job_b:
    needs: job_a
    runs-on: ubuntu-latest
    steps:
      - run: echo "A step in job B"
  job_c:
    needs: job_b
    runs-on: ubuntu-latest
    steps:
      - run: echo "A step in job C"
